spring:
  datasource:
    url: ENC(TdV0eYAL3LSlvbDFTztpiKz9tOxKWlCzeITpstvd8fndTDbS+DCNhbVIccLTxm73j7uwc84+1N03zraodFE1e7EC5oU6k/10+OWp25LN/xxRDwXmyMbw+ZqJiwJLbMel)
    username: ENC(beDx2gXAeAxV+VZd/SkiqMaczaTm3Rj2l0TpY8ogShokNlnu6tVAdjmdpC7o1aSC)
    password: ENC(4SyrWZHyzfkDQqeynwC4NEiGEME4hSF5EDy6TcXnQ864Fuggclf00RrBFbWYu9m0)

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  algorithm: RS256
  issuer: hooni-template-auth
  audience: hooni-template-api
  jwk-set-uri: http://auth-api-service.auth.svc/oauth2/jwks
